--CREAR BASE DE DATOS
create database dbElectrodomesticos
go

--PONER EN USO LA BASE DE DATOS
USE dbElectrodomesticos
go

--CREACION DE TABLAS
create table CLIENTE(
CODCLI CHAR(4),
NOMCLI VARCHAR(60),
APECLI VARCHAR(60),
EMACLI VARCHAR(80),
CELCLI CHAR(9),
DIRCLI VARCHAR(70),
ESTCLI CHAR(1)
CONSTRAINT CLIENTE_PK PRIMARY KEY (CODCLI)
)
GO


CREATE TABLE VENDEDOR(
CODVEND CHAR(4),
NOMVEND VARCHAR(60),
APEVEND VARCHAR(80),
EMAVEND VARCHAR(80),
CELVEND CHAR(9),
DIRVEND VARCHAR(70),
ESTVEND CHAR(1)
CONSTRAINT VENDEDOR_PK PRIMARY KEY (CODVEND) 
)
GO

CREATE TABLE PRODUCTO(
CODPRO CHAR(5),
DESCPRO VARCHAR(80),
CATPRO CHAR(1),
PREPRO DECIMAL(8,2),
STOCKPRO INT,
ESTPRO CHAR(1)
CONSTRAINT PRODUCTO_PK PRIMARY KEY (CODPRO)
)
GO

CREATE TABLE PROVEEDOR (
CODPROV CHAR(5),
RAZSOCPROV VARCHAR(90),
RUCPROV VARCHAR(11),
EMAPROV VARCHAR(70),
ESTPROV CHAR(1)
CONSTRAINT PROVEEDOR_PK PRIMARY KEY(CODPROV)
)
GO

CREATE TABLE VENTA(
CODVEN CHAR(5),
FECVEN DATETIME,
CODCLI CHAR(4),
CODVEND CHAR(4),
ESTVEN CHAR(1)
CONSTRAINT VENTA_PK PRIMARY KEY (CODVEN)
)
GO

CREATE TABLE VENTADETALLE(
IDVENDET INT,
CODVEN CHAR(5),
CODPRO CHAR(5),
CANTPRO INT
CONSTRAINT VENTADETALLE_PK PRIMARY KEY (IDVENDET)
)
GO

CREATE TABLE COMPRA(
CODCOM CHAR(5),
FECCOM DATETIME,
CODVEND CHAR(4),
CODPROV CHAR(5),
ESTCOM CHAR(1)
CONSTRAINT COMPRA_PK PRIMARY KEY (CODCOM)
)
GO

CREATE TABLE COMPRADETALLE(
IDCOMDET INT,
CODCOM CHAR(5),
CODPRO CHAR(5),
CANTPRO INT
CONSTRAINT COMPRADETALLE_PK PRIMARY KEY (IDCOMDET)
)
GO

--RELACIONES ENTRE TABLAS
ALTER TABLE VENTA
ADD CONSTRAINT FK_VENTACLIENTE
FOREIGN KEY (CODCLI) REFERENCES CLIENTE(CODCLI)
GO

ALTER TABLE VENTA
ADD CONSTRAINT FK_VENTAVENDEDOR
FOREIGN KEY (CODVEND) REFERENCES VENDEDOR(CODVEND)
GO

ALTER TABLE COMPRA
ADD CONSTRAINT FK_COMPRA_VENDERDOR
FOREIGN KEY (CODVEND) REFERENCES VENDEDOR(CODVEND)
GO

ALTER TABLE COMPRA
ADD CONSTRAINT FK_COMPRA_PROVEEDOR
FOREIGN KEY (CODPROV) REFERENCES PROVEEDOR(CODPROV)
GO

ALTER TABLE VENTADETALLE
ADD CONSTRAINT FK_VENTADETALLE_VENTA
FOREIGN KEY (CODVEN) REFERENCES VENTA(CODVEN)
GO

ALTER TABLE VENTADETALLE
ADD CONSTRAINT FK_VENTADETALLE_PRODUCTO
FOREIGN KEY (CODPRO) REFERENCES PRODUCTO(CODPRO)
GO

ALTER TABLE COMPRADETALLE
ADD CONSTRAINT FK_COMPRADETALLE_COMPRA
FOREIGN KEY (CODCOM) REFERENCES COMPRA(CODCOM)
GO

ALTER TABLE COMPRADETALLE
ADD CONSTRAINT FK_COMPRADETALLEPRODUCTO
FOREIGN KEY (CODPRO) REFERENCES PRODUCTO(CODPRO)
GO

CREATE PROCEDURE  SPINSERTCLIENTE
(
@CODCLI CHAR(4),
@NOMCLI VARCHAR(60),
@APECLI VARCHAR(80),
@EMACLI VARCHAR(80),
@CELCLI CHAR(9),
@DIRCLI VARCHAR(70),
@ESTCLI CHAR(1)
)
AS BEGIN
	INSERT INTO CLIENTE (CODCLI,NOMCLI,APECLI,EMACLI,CELCLI,DIRCLI,ESTCLI)
	VALUES (@CODCLI,@NOMCLI,@APECLI,@EMACLI,@CELCLI,@DIRCLI,@ESTCLI)
END

EXEC SPINSERTCLIENTE @CODCLI,@NOMCLI,@APECLI,@EMACLI,@CELCLI,@DIRCLI,@ESTCLI
SELECT
'CL01','Juana','Campos Ortíz','juana.campos@gmail.com','987485152','Av. Miraflores','A'
GO

INSERT INTO CLIENTE (CODCLI,NOMCLI,APECLI,EMACLI,CELCLI,DIRCLI,ESTCLI)
VALUES
('CL01','Juana','Campos Ortíz','juana.campos@gmail.com','987485152','Av. Miraflores','A'),
('CL02','Sofia','Barrios Salcedo','sofia.barrios@outlook.com','','Av. Libertadores','A'),
('CL03','Claudio','Perez Luna','claudio.perez@outook.com','984512147','Av. Libertadores','A'),
('CL04','Marcos','Avila Manco','marcos.avila@yahoo.com','','Calle Huallaga','A'),
('CL05','Anastasio','Salomon Inti','anastasio.salomon@gmail.com','','Jr. San Martin','A');

SELECT * FROM CLIENTE;


INSERT INTO VENDEDOR (CODVEND,NOMVEND,APEVEND,EMAVEND,CELVEND,DIRVEND,ESTVEND)
values
('VEN1','Gloria','Carrizales Paredes','gloria.carrizales@gmail.com','984557123','Calle Las Begonias','A'),
('VEN2','Gabriela','Lozada Lombardi','gabriel.lozada@gmail.com','974512368','Av. Los Girasoles','A'),
('VEN3','Gilberto','Martinez Guerra','gilberto.martinez@gmail.com','','Jr. Palomares','A');

SELECT * FROM VENDEDOR;


INSERT INTO PROVEEDOR (CODPROV,RAZSOCPROV,RUCPROV,EMAPROV,ESTPROV)
VALUES
('PRV01','LG Corporation','87542136951','imformes@lg.com.pe','A'),
('PRV02','SONY','45213698741','imformes@sony.com.pe','A'),
('PRV03','SANSUNG','85321697661','imformes@samsung.com.pe','A'),
('PRV04','OSTER SRL','55663214478','imformes@oster.com.pe','A'),
('PRV05','ASUS','99663325478','imformes@asus.com.pe','A');

SELECT * FROM PROVEEDOR;

INSERT INTO PRODUCTO (CODPRO,DESCPRO,CATPRO,PREPRO,STOCKPRO,ESTPRO)
VALUES
('PRO01','Refrigeradora LG Side By Side',1,4149,15,'A'),
('PRO02','Refrigeradora SBS 602L',1,3599,10,'A'),
('PRO03','Refrigeradora Top Mount 500 L',1,2799,8,'A'),
('PRO04','TV SAMSUNG UHD 55',2,1799,25,'A'),
('PRO05','Televisor 65 LG UHD 4K',2,2999,20,'A'),
('PRO06','TV CRYSTAL UHD 55',2,2299,7,'A'),
('PRO07','ASUS X415JA Core i3 10a Gen 14',3,1099,17,'A'),
('PRO08','Lenovo IdeaPad 5i Intel Core i7 14',3,3099,10,'A'),
('PRO09','Laptop HP 15-dw1085la Intel Core i3',3,1600,15,'A'),
('PRO10','Galaxy A52 128GB',4,1200,25,'A'),
('PRO11','iPhone 11 64GB Morado',4,2600,30,'A'),
('PRO12','Poco X3 GT 5G 256GB 8GB',4,1450,20,'A');

SELECT * FROM PRODUCTO;

insert into VENTA (CODVEN,FECVEN,CODCLI,CODVEND,ESTVEN)
VALUES
('VEN01','1/07/2022','CL01','VEN1','A'),
('VEN02','1/07/2022','CL02','VEN2','A'),
('VEN03','1/07/2022','CL03','VEN3','A');

SELECT * FROM VENTA;

CREATE PROCEDURE SPCOMPRA
(
@CODCOMP CHAR(5),
@FECCOMP DATETIME,
@CODVEND CHAR(4),
@COSPROV CHAR(5),
@ESTCOM CHAR(1)
)
AS BEGIN
	INSERT INTO COMPRA (CODCOM,FECCOM,CODVEND,CODPROV,ESTCOM)
	VALUES (@CODCOMP,@FECCOMP,@CODVEND,@COSPROV,@ESTCOM)

	/*DECLARE @MAXIMO CHAR(5),
	@MAXIMO = SELECT MAX(CODCOM) FROM COMPRA;

	DECLARE @IDCOMDET CHAR(5),
	@CODPRO CHAR(5),
	@CANTPRO INT

	INSERT INTO COMPRADETALLE (IDCOMDET,CODCOM,CODPRO,CANTPRO)
	VALUES(@IDCOMDET,@MAXIMO,@CODPRO,@CANTPRO)*/
END

EXEC SPCOMPRA 'COM01','1/07/2022','VEN1','PRV01','A';

